# Generated by Django 4.2.1 on 2023-12-26 08:34

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('tcp_portal', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='tbl_authenticate',
        ),
        migrations.AlterModelManagers(
            name='tbl_authenticate',
            managers=[
                ('empAuth_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
