# Generated by Django 5.0 on 2023-12-27 16:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcp_portal', '0003_userprofile_delete_tbl_authenticate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('authflag_count', models.IntegerField(blank=True, default=0, null=True)),
                ('publicflag_count', models.IntegerField(blank=True, default=0, null=True)),
                ('publicflag_ip', models.GenericIPAddressField()),
                ('autoflag_count', models.IntegerField(blank=True, default=0, null=True)),
                ('autoflag_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('authflag_accounts', models.ManyToManyField(blank=True, related_name='authflag_ips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
