# Generated by Django 5.0 on 2023-12-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcp_portal', '0004_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ip',
            name='ip',
        ),
        migrations.AddField(
            model_name='ip',
            name='overall_ip',
            field=models.GenericIPAddressField(default='0.0.0.0', unique=True),
        ),
        migrations.RemoveField(
            model_name='ip',
            name='authflag_accounts',
        ),
        migrations.AlterField(
            model_name='ip',
            name='autoflag_ip',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='ip',
            name='publicflag_ip',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='ip',
            name='authflag_accounts',
            field=models.TextField(default='[]'),
        ),
    ]
