# Generated by Django 5.0 on 2023-12-28 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcp_portal', '0005_remove_ip_ip_ip_overall_ip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip',
            name='overall_ip',
            field=models.CharField(default='0.0.0.0', max_length=64, unique=True),
        ),
    ]
